POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1paSIsImlkIjoiNjNmMzY3NzliZDc2NThjYzYwNmM4MmFmIiwiaWF0IjoxNjc2ODk2MTU3LCJleHAiOjE2NzY4OTk3NTd9.0DAXUA4nlm4lba6R8vt-NclPJkDacbNUemfDh47EJlY

{
    "title": "uusi blog 5",
    "author": "title 5",
    "url": "url 5",
    "likes": "105"
}